#!/bin/bash
# Pre-requisite: Run test-authn-jwt scripts to ensure JWT is configured and valid

# Load shared configuration and JWT-specific variables
source ../00.config.sh
source ../test-authn-jwt/00.config.sh

# Verify if the environment is ready for execution
if [[ "$READY" != "true" ]]; then
    echo "Your configuration is not ready. Set READY=true in 00.config.sh"
    exit 1
fi

# Path to the JWT token generated by your identity provider (e.g., GitLab CI/CD)
export JWT_TOKEN_PATH="../test-authn-jwt/data/jwt"

if [ ! -f "$JWT_TOKEN_PATH" ]; then
    echo "Error: JWT token file not found at $JWT_TOKEN_PATH."
    exit 1
fi

# --- Conjur Connection Settings ---
export CONJUR_APPLIANCE_URL="https://conjur.$POC_DOMAIN:$POC_CONJUR_HTTPS_PORT"
export CONJUR_ACCOUNT="$POC_CONJUR_ACCOUNT"
export CONJUR_CERT_FILE="./conjur-server.pem"

# --- Certificate Generation Logic ---
# Automatically fetch the Conjur server certificate if it doesn't exist locally
if [ ! -f "$CONJUR_CERT_FILE" ]; then
    echo "Certificate $CONJUR_CERT_FILE not found. Fetching from $CONJUR_APPLIANCE_URL..."
    
    # Extract Host and Port for OpenSSL connection
    HOST="conjur.$POC_DOMAIN"
    PORT="${POC_CONJUR_HTTPS_PORT:-443}"
    
    openssl s_client -showcerts -connect "$HOST:$PORT" < /dev/null 2> /dev/null | \
    sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > "$CONJUR_CERT_FILE"
    
    if [ -s "$CONJUR_CERT_FILE" ]; then
        echo "Successfully created $CONJUR_CERT_FILE"
    else
        echo "Error: Failed to fetch certificate. Check network or Conjur URL."
        exit 1
    fi
fi

# --- JWT Authenticator Configuration ---
export CONJUR_AUTHN_JWT_SERVICE_ID="$JWT_SERVICE_ID"
export CONJUR_AUTHN_LOGIN="host/$JWT_HOST_ID"

# Clear conflicting variables to ensure Summon uses JWT authentication
unset CONJUR_AUTHN_TOKEN_FILE
unset CONJUR_AUTHN_API_KEY

# --- Execution ---
set -x

# Summon fetches secrets defined in the YAML and injects them into the sub-process
# PASSWORD will be available as an environment variable within test.sh
summon --yaml "PASSWORD: !var test/host1/pass" ./test.sh

set +x